spring:
  # 💡 FORCE SPRING BOOT TO READ LOCAL ENVIRONMENT AND CHILD YAML PROFILES
  config:
    import: 
      - "optional:file:.env"
      - "optional:classpath:application-mail.yml"  # 🟢 Imports email setup
      - "optional:classpath:application-app.yml"   # 🟢 Imports app configurations

  application:
    name: pp_api

  docker:
    compose:
      enabled: false
  
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/opoppr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA / Hibernate Configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  # Liquibase Migration Configuration
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/master.yaml"
    drop-first: false

server:
  port: 9000
