spring:
  # 💡 FORCE SPRING BOOT TO READ LOCAL ENVIRONMENT PARAMETERS (.env)
  config:
    import: "optional:file:.env"

  application:
    name: pp_api

  docker:
    compose:
      enabled: false
  
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/opoppr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA / Hibernate Configurations
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  # Liquibase Migration Configuration
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/master.yaml"
    drop-first: false

# Custom Application Metrics (Moved completely out of spring root block)
application:
  security:
    argon2:
      salt-length: 16       # Length of the random salt in bytes (16 bytes = 128 bits)
      hash-length: 32       # Length of the generated hash in bytes
      parallelism: 1        # Number of threads used for computation
      memory: 65536         # Memory cost in KiB (65536 KiB = 64 MiB)
      iterations: 3         # CPU cost / number of passes over the memory

server:
  port: 9000
